export enum DataSheetEnum {
  id = "ID",
  entity_type = "Entity Type",
  legal_name = "Legal Name",
  dba_name = "DBA Name",
  physical_address = "Physical Address",
  p_street = "P Street",
  p_city = "P City",
  p_state = "P State",
  p_zip_code = "P Zip Code",
  phone = "Phone",
  mailing_address = "Mailing Address",
  m_street = "M Street",
  m_city = "M City",
  m_state = "M State",
  m_zip_code = "M Zip Code",
  usdot_number = "USDOT Number",
  power_units = "Power Units",
  mcs_150_form_date = "MCS 150 Form Date",
  drivers = "Drivers",
  mcs_150_mileage_year = "MCS 150 Mileage Year",
  credit_score = "Credit Score",
  record_status = "Record Status",
  created_dt = "Created At",
  data_source_modified_dt = "Data Source Modified",
}

export enum CarrierDataFields {
  CREATED_DT = "created_dt",
  DATA_SOURCE_MODIFIED_DT = "data_source_modified_dt",
  ENTITY_TYPE = "entity_type",
  LEGAL_NAME = "legal_name",
  DBA_NAME = "dba_name",
  PHYSICAL_ADDRESS = "physical_address",
  P_STREET = "p_street",
  P_CITY = "p_city",
  P_STATE = "p_state",
  P_ZIP_CODE = "p_zip_code",
  PHONE = "phone",
  MAILING_ADDRESS = "mailing_address",
  M_STREET = "m_street",
  M_CITY = "m_city",
  M_STATE = "m_state",
  M_ZIP_CODE = "m_zip_code",
  USDOT_NUMBER = "usdot_number",
  POWER_UNITS = "power_units",
  MCS_150_FORM_DATE = "mcs_150_form_date",
  DRIVERS = "drivers",
  MCS_150_MILEAGE_YEAR = "mcs_150_mileage_year",
  ID = "id",
  CREDIT_SCORE = "credit_score",
  RECORD_STATUS = "record_status",
}

export enum RecordStatusEnum {
  ACTIVE = "active",
  INACTIVE = "inactive",
}
